<?php

namespace User\BlocNoteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * reportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reportRepository extends EntityRepository
{
}
