<?php

namespace User\UserBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class StudentController__JMSInjector
{
    public static function inject($container) {
        $instance = new \User\UserBundle\Controller\StudentController();
        return $instance;
    }
}
